name: LunaAchievement
version: '${project.version}'
main: kr.lunaf.achievement.LunaAchievement
api-version: 1.21
commands:
  reloadachievements:
    description: 업적 리로드
    usage: /reloadachievements
    permission: achievementplugin.reloadachievements
    permission-message: 권한 부족
permissions:
  achievementplugin.reloadachievements:
    description: 리로드 권한
    default: op

